name: Auto Update and Deploy Website

on:
  push:
    branches: [ main ] # mainブランチにpush時に実行
  schedule:
    - cron: '0 18 * * *' # 日本時間の朝3時に実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Pythonセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: config.yamlを生成
        run: |
          echo "openai_api_key: ${{ secrets.OPENAI_API_KEY }}" > data/scripts/config.yaml

      - name: AIによるサイト自動修復（Pythonスクリプトを実行）
        run: python data/scripts/ai_auto_update.py

      - name: サーバーへのデプロイ（コード更新）
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/stock-strategy-site
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flask-stock-site
