name: Deploy to VPS (Flask App)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pythonのセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/stock-strategy-site
            git pull origin main || true
            source venv/bin/activate
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            else
              echo "requirements.txt not found, skipping pip install."
            fi
            sudo systemctl restart flask-stock-site.service || echo "Flask service restart failed."
